<h1> Week 5: machine learning </h1>

For this assignment I picked the Employee Attrition dataset.

In [1]:
import seaborn as sns
import sklearn as sk
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
df = pd.read_csv('Employee-Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
df['Attrition'].value_counts()

No     1233
Yes     237
Name: Attrition, dtype: int64

In [4]:
# first off we need dummy variables to be ablo to predict Attrition, it is now Yes and No. This has to be 0 and 1. 
# i use concat to add the dummy values to the df
dummies = pd.get_dummies(df['Attrition'])
df = pd.concat([df, dummies], axis=1) 
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,No,Yes
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,0,8,0,1,6,4,0,5,0,1

In [5]:
# now that attrition has dummies I can look at it in the correlation matrix
df.corr()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,No,Yes
Age,1.000000,0.010661,-0.001686,0.208034,NaN,-0.010145,0.010146,0.024287,0.029820,0.509604,...,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089,0.159205,-0.159205
DailyRate,0.010661,1.000000,-0.004985,-0.016806,NaN,-0.050990,0.018355,0.023381,0.046135,0.002966,...,0.042143,0.014515,0.002453,-0.037848,-0.034055,0.009932,-0.033229,-0.026363,0.056652,-0.056652
DistanceFromHome,-0.001686,-0.004985,1.000000,0.021042,NaN,0.032916,-0.016075,0.031131,0.008783,0.005303,...,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406,-0.077924,0.077924
Education,0.208034,-0.016806,0.021042,1.000000,NaN,0.042070,-0.027128,0.016775,0.042438,0.101589,...,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065,0.031373,-0.031373
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeNumber,-0.010145,-0.050990,0.032916,0.042070,NaN,1.000000,0.017621,0.035179,-0.006888,-0.018519,...,0.062227,-0.014365,0.023603,0.010309,-0.011240,-0.008416,-0.009019,-0.009197,0.010577,-0.010577
EnvironmentSatisfaction,0.010146,0.018355,-0.016075,-0.027128,NaN,0.017621,1.000000,-0.049857,-0.008278,0.001212,...,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999,0.103369,-0.103369
HourlyRate,0.024287,0.023381,0.031131,0.016775,NaN,0.035179,-0.049857,1.000000,0.042861,-0.027853,...,0.050263,-0.002334,-0.008548,-0.004607,-0.019582,-0.024106,-0.026716,-0.020123,0.006846,-0.006846
JobInvolvement,0.029820,0.046135,0.008783,0.042438,NaN,-0.006888,-0.008278,0.042861,1.000000,-0.012630,...,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976,0.130016,-0.130016
JobLevel,0.509604,0.002966,0.005303,0.101589,NaN,-0.018519,0.001212,-0.027853,-0.012630,1.000000,...,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281,0.169105,-0.169105
JobSatisfaction,-0.004892,0.030571,-0.003669,-0.011296,NaN,-0.046247,-0.006784,-0.071335,-0.021476,-0.001944,...,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656,0.103481,-0.103481
MonthlyIncome,0.497855,0.007707,-0.017014,0.094961,NaN,-0.014829,-0.006259,-0.015794,-0.015271,0.950300,...,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079,0.159840,-0.159840
MonthlyRate,0.028051,-0.032182,0.027473,-0.026084,NaN,0.012648,0.037600,-0.015297,-0.016322,0.039563,...,-0.034323,0.026442,0.001467,0.007963,-0.023655,-0.012815,0.001567,-0.036746,-0.015170,0.015170
NumCompaniesWorked,0.299635,0.038153,-0.029251,0.126317,NaN,-0.001251,0.012594,0.022157,0.015012,0.142501,...,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319,-0.043494,0.043494
PercentSalaryHike,0.003634,0.022704,0.040235,-0.011111,NaN,-0.012944,-0.031701,-0.009062,-0.017205,-0.034730,...,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985,0.013478,-0.013478
PerformanceRating,0.001904,0.000473,0.027110,-0.024539,NaN,-0.020359,-0.029548,-0.002172,-0.029071,-0.021222,...,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827,-0.002889,0.002889
RelationshipSatisfaction,0.053535,0.007846,0.006557,-0.009118,NaN,-0.069861,0.007665,0.001330,0.034297,0.021642,...,-0.045952,0.024054,0.002497,0.019604,0.019367,-0.015123,0.033493,-0.000867,0.045872,-0.045872
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,0.037510,0.042143,0.044872,0.018422,NaN,0.062227,0.003432,0.050263,0.021523,0.013984,...,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698,0.137145,-0.137145
TotalWorkingYears,0.680381,0.014515,0.004628,0.148280,NaN,-0.014365,-0.002693,-0.002334,-0.005533,0.782208,...,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188,0.171063,-0.171063
TrainingTimesLastYear,-0.019621,0.002453,-0.036942,-0.025100,NaN,0.023603,-0.019359,-0.008548,-0.015338,-0.018191,...,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096,0.059478,-0.059478
WorkLifeBalance,-0.021490,-0.037848,-0.026556,0.009819,NaN,0.010309,0.027627,-0.004607,-0.014617,0.037818,...,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759,0.063939,-0.063939
YearsAtCompany,0.311309,-0.034055,0.009508,0.069114,NaN,-0.011240,0.001458,-0.019582,-0.021355,0.534739,...,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212,0.134392,-0.134392
YearsInCurrentRole,0.212901,0.009932,0.018845,0.060236,NaN,-0.008416,0.018007,-0.024106,0.008717,0.389447,...,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365,0.160545,-0.160545
YearsSinceLastPromotion,0.216513,-0.033229,0.010029,0.054254,NaN,-0.009019,0.016194,-0.026716,-0.024184,0.353885,...,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224,0.033019,-0.033019
YearsWithCurrManager,0.202089,-0.026363,0.014406,0.069065,NaN,-0.009197,-0.004999,-0.020123,0.025976,0.375281,...,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000,0.156199,-0.156199
No,0.159205,0.056652,-0.077924,0.031373,NaN,0.010577,0.103369,0.006846,0.130016,0.169105,...,0.137145,0.171063,0.059478,0.063939,0.134392,0.160545,0.033019,0.156199,1.000000,-1.000000
Yes,-0.159205,-0.056652,0.077924,-0.031373,NaN,-0.010577,-0.103369,-0.006846,-0.130016,-0.169105,...,-0.137145,-0.171063,-0.059478,-0.063939,-0.134392,-0.160545,-0.033019,-0.156199,-1.000000,1.000000

In [6]:
# based on the correlations I picked the following variables
df_subset = df[['Yes','YearsInCurrentRole', 'TotalWorkingYears', 'JobLevel', 'Age', 'MonthlyIncome', 'YearsWithCurrManager', 'YearsAtCompany']]
df_subset.head()

,Yes,YearsInCurrentRole,TotalWorkingYears,JobLevel,Age,MonthlyIncome,YearsWithCurrManager,YearsAtCompany
0,1,4,8,2,41,5993,5,6
1,0,7,10,2,49,5130,7,10
2,1,0,7,1,37,2090,0,0
3,0,7,8,1,33,2909,0,8
4,0,2,6,1,27,3468,2,2

<h2> K- nearest neighbour</h2>

In [7]:
from sklearn.preprocessing import normalize #get the function needed to normalize our data.

X = df_subset[['YearsInCurrentRole', 'TotalWorkingYears', 'JobLevel', 'Age', 'MonthlyIncome', 'YearsWithCurrManager', 'YearsAtCompany']] #create the X matrix
X = normalize(X) #normalize the matrix to put everything on the same scale
y = df_subset['Yes'] #create the y-variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) #split the data, store it into different variables

In [8]:
from sklearn.neighbors import KNeighborsClassifier #the object class we need

knn = KNeighborsClassifier(n_neighbors=5) #create a KNN-classifier with 5 neighbors (default)
knn = knn.fit(X_train, y_train) #this fits the k-nearest neigbor model with the train data
knn.score(X_test, y_test) #calculate the fit on the test data

0.8253968253968254

In [9]:
from sklearn.metrics import confusion_matrix
y_test_pred = knn.predict(X_test) #the predicted values
cm = confusion_matrix(y_test, y_test_pred) #creates a "confusion matrix"
cm

array([[357,   7],
       [ 70,   7]], dtype=int64)

In [10]:
#In order to read it, I made a confusion matrix in a table and added the labels
conf_matrix = pd.DataFrame(cm, index=['No Attrition', 'Attrition'], columns = ['No Attrition_p', 'Attrition_p']) 
conf_matrix

              No Attrition_p  Attrition_p
No Attrition             357            7
Attrition                 70            7

In [11]:
# calculating f1-score, recall and precision 

from sklearn.metrics import classification_report
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.84      0.98      0.90       364
           1       0.50      0.09      0.15        77

   micro avg       0.83      0.83      0.83       441
   macro avg       0.67      0.54      0.53       441
weighted avg       0.78      0.83      0.77       441